### PR TITLE
Update to middleman 4.1.1 and fix :ignore option

### PR DESCRIPTION
**Pull request by adam-h**
This should also work on middleman 4.0, but I have not tested that.

Documentation was unclear as to how the `:ignore` option should work, but it didn't seem to be working :( So this makes it accept regular expressions.

### CODE REVIEW

**Comment by tdreyno** [comment]
This gem should support both versions 3 and 4, so we don't want to make backwards incompatible changes.

**Comment by jessepollak** [comment]
+1 for this change

**Comment by tdreyno** [comment]
Me too, the actual fix is unrelated to dropping 3.x support.

**Comment by jessepollak** [comment]
I can put in the work to make this work, if I understand the compatibility issue. Would dropping everything except for the `ignore` specific changes at 46 and 71 (and making them support both forms) be the right way to proceed?

**Comment by tdreyno** [comment]
Seems like the only necessary change is making the two guard clauses (the `next` bit) also take into account the `ignore.any? { |i| file.to_s.match(i) }` ... But, it should continue to also use the Middleman-wide ignore, which is that `respond_to` stuff because that API changed between v3/v4.

**Comment by tdreyno** [comment]
So, ignore it if it fails either the MM list or the `ignore` list

**Comment by pdlug** [comment]
Any reason this hasn't been merged in yet? It would be really helpful to have working `ignore` functionality w/ livereload in MM 4.x

**Comment by jessepollak** [comment]
@pdlug this was fixed by #91 and I think this PR can be closed without merging.

**Pull request closed without merging**
